version: '3.8'
services:
  db:
    image: postgres:14 # Sử dụng ảnh postgres phiên bản 14
    container_name: bistro_bliss_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bistro_bliss
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: